"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, { useState } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [num, setnum] = useState(10);
  const [show, setshow] = useState([
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
  ]);
  return (
    <html data-theme={show[num]} lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          style={{
            height: "90vh",
            display: "flex",
            width: "100%",
            alignItems: "center",
            justifyContent: "center",
            gap: "30px",
          }}
        >
          <h1>Choose the theme you want </h1>
          <>
            <button
              className="btn btn-active btn-neutral"
              onClick={() => {
                setnum(num + 1);
              }}
            >
              Forward
            </button>
            <button className="btn btn-active btn-primary">{show[num]}</button>
            <button
              className="btn btn-active btn-secondary"
              onClick={() => {
                setnum(num - 1);
              }}
            >
              backward
            </button>
          </>
        </div>

        {children}
      </body>
    </html>
  );
}
